[theme]
primaryColor = "#F63366"
backgroundColor = "grey"
secondaryBackgroundColor = "#aaaaaa"
[server]
sslCertFile = 'C:\\Users\\ngautam\\Manage Inventory\\cert.pem'
sslKeyFile = 'C:\\Users\\ngautam\\Manage Inventory\\key.pem'

